[Step 2] jaegeun, ttobagi
tasty-code/ios-exposition-universelle pull request #10
Opened 2022-09-23 07:43 UTC by moonsoungjin

Step 2 설명
- ScrollView를 활용해 많은 콘텐츠를 화면에 담음
- stackView를 통해 컴포넌트 그룹화
- tableView Delegate를 활용해 셀을 클릭하였을 때 화면 이동
- Auto LayOut을 통해 여러화면에서도 잘 보이게 구현
- Json데이터를 파싱 후 유저가 볼수있게 구현
- tableView구현

2022-09-26 09:56 UTC, jaemuYeo requested changes
또바기 재근 Step2도 고생많았습니다!
이번 스텝에서의 목표는 데이터를 파싱해서 UI에 업데이트 시키는 것이 가장 중요한 주제입니다~
그 부분에 대해서는 잘 해결해주었군요!👏
다만 어떻게 하면 중복된 코드를 방지할 수있고,
재사용성이 용이한지에 대한 부분을 코멘트에 남길까해요~
코멘트 참고해서 반영 후 재요청부탁해요!!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +        super.prepareForReuse()
오버라이딩의 super. 아래로는 한번개행해주면 가독성이 좋습니다!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    }
개행이 안되었어요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +class DescriptionViewController: UIViewController {
네이밍이 조금 모호한것 같아요🤔 `어떤 것`의 설명을 담은 뷰컨트롤러 인가요?

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    var workName: String = ""
중복된 데이터타입 값을 사용할때는 예~전에 공유했던
static let을 통해 사용해볼 수 있을 것같습니다 ㅎㅎ
방법은 두가지로 추려볼 수 있을 것같아요
```swift
enum Constants {
    static let emptyString = ""
}

extension String {
    static let empty = ""
}

var workName: String = .empty
var workImageName: String = .empty
var workDescription: String = Contants.emptyString
```
(이럴 때 쓰면 돼요! 예전에 static let 남발해서 빠꾸당한적 있지요?☺️)

---

다만 위 세개의 변수는 itemListViewController의 테이블뷰 딜리게이트로 정보를 넣어주고 있는대요
다른 방법으로 조금 더 간편하게 데이터를 전달할 수있는 방법은 없을까요??
item타입을 해당 VC에서 가지고 있으면 `item.` 을 통해 정보를 담을 수 있을 것같아요☺️

Hint. 데이터 전달 - prepare, view life cycle

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    private func settingViewController() {
은닉화 좋아요 👍
다만 네이밍이 조금 고민이 되는대요!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    }
중괄호가 끝나는 부분에서 개행해주면 읽기 편할 거같아요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    override func viewDidLoad() {
컨벤션 차이겠지만 저는 보통 메서드 위에 뷰라이프사이클을 배치합니다!
아래에 작성한 이유가 있나요?

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +    @IBOutlet weak var workListTableView: UITableView!
저는 보통 아웃렛변수를 제일 상단에 두는 편입니다! 🙂

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +    }
개힝이 안되어있네요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +
불필요한 개행입니다~!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +extension KoreaWorkListViewController: UITableViewDelegate {
prepare를 오버라이딩해 사용한다면 해당 delegate는 불필요할 것같아요!!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        guard let cell = workListTableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as? WorkListTableViewCell else { return UITableViewCell() }
cell의 Identifier가 일반적인 cell이 아닌 어떤셀인지 더 명확했으면 좋겠어요~
그리고 데이터 타입의 값은 바로 담기보다는
이 곳에서만 쓰인다면 메서드 내부에 상수로 선언 후 담아두거나
다방면에서 재사용된다면 DescriptionVC의 빈문자열 처리방법 코멘트를 참고해서 사용해보세요!

이렇게 하는 이유는 무엇일까요?

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        cell.workImageView.image = UIImage(named: items[indexPath.row].imageName)
guard문, cell 셋팅, return문 사이에 한번씩의 개행이 있으면 가독성이 좋아질 거같아요~

WorkListTableViewCell에서 Cell을 구성하는 메서드를 만들면
이 곳에서 메서드 호출을 통해 한줄로 구현 가능할 것같아요 🙂

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +
불필요한 개행입니다!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +class StartViewController: UIViewController {
해당 VC는 PerserJSON의 코멘트를 처리후에 다시 보도록 할게요!!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +
불필요한 개행입니다!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
한 번 개행해주세요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +    func DecimalWon(value: Int) -> String{
한 번 개행해주세요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +    }
한 번 개행해주세요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +        super.viewDidLoad()
한 번 개행해주세요~

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +import Foundation
UIKit만 import해도 될 것같아요~
왜 그럴까요?

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +class PerserJSON {
Perser인가요 Parser인가요??

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +
불필요한 개행입니다!

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +    func persingExpositionJSON(_ jsonData: NSDataAsset) throws -> Exposition {
persingExpositionJSON메서드와 persingItemJSON의 네이밍은 persing인가요 parsing인가요??🤔

현재 두 메서드에서 반복적으로 사용되는 코드가 있어요~
만약 디코딩해야하는 데이터가 100페이지가 된다면 해당 작업을 100번 코드에 넣어야하는데
효율적일까요??

어떻게 처리해볼 수 있을까요?? 고민해보시고 잘 모르겠다생각이들면 저에게 알려주세요😀

2022-09-26 09:56 UTC, jaemuYeo commented on Expo1900/Expo1900/Error/ExpoError.swift
> +enum ExpoError: Error, LocalizedError {
에러타입을 잘 구현해 주었네요! 멋져요 💯

2022-09-28 00:57 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +        super.prepareForReuse()
넵

2022-09-28 00:57 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    }
넵

2022-09-28 00:57 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +class DescriptionViewController: UIViewController {
작품에 관한 디테일 설명이니 WorkDescription이 좋은거같습니다.

2022-09-28 00:58 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    var workName: String = ""
하나하나 넘기는것보다 객체를 넘기는것이 좀더 좋은방법같네요!

2022-09-28 01:02 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    override func viewDidLoad() {
함수의 흐름을 지키기위해 그렇게 하였습니다. 잼킹이 라이프 사이클을 메서드위에 쓰시는 이유도 들어보고 싶습니다!

2022-09-28 01:02 UTC, moonsoungjin commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    private func settingViewController() {
settingViewController를 configure로 바꿔주었습니다

2022-09-28 01:03 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +    @IBOutlet weak var workListTableView: UITableView!
저도 한번 해보겠습니다!

2022-09-28 01:11 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        cell.workImageView.image = UIImage(named: items[indexPath.row].imageName)
넵

2022-09-28 01:12 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +
넵

2022-09-28 01:13 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +
넵

2022-09-28 01:13 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
넵

2022-09-28 01:13 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +    func DecimalWon(value: Int) -> String{
넵

2022-09-28 01:13 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +    }
넵

2022-09-28 01:13 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +        super.viewDidLoad()
넵

2022-09-28 01:14 UTC, wormsJJG commented on Expo1900/Expo1900/Error/ExpoError.swift
> +enum ExpoError: Error, LocalizedError {
ㅎㅎ

2022-09-28 01:15 UTC, wormsJJG commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +    func persingExpositionJSON(_ jsonData: NSDataAsset) throws -> Exposition {
넵

2022-09-28 01:17 UTC, moonsoungjin commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +
넵!

2022-09-28 01:17 UTC, moonsoungjin commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    }
넵!

2022-09-28 01:17 UTC, moonsoungjin commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +    }
넵!

2022-09-28 01:17 UTC, moonsoungjin commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +
넵!!

2022-09-28 01:28 UTC, wormsJJG commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +class PerserJSON {
parser입니다.

2022-09-28 01:28 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +extension KoreaWorkListViewController: UITableViewDelegate {
냅

2022-09-28 01:30 UTC, wormsJJG commented on Expo1900/Expo1900/Model/PerserJSON.swift
> +import Foundation
JSONDecoder와, NSDataAsset을 사용하려면 UIKit이 임포트 되어야 하기 때문입니다. Foundation은 임포트안해줘도 되겠네요!

2022-09-28 01:49 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        guard let cell = workListTableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as? WorkListTableViewCell else { return UITableViewCell() }
cell 내부에 값을 매칭해주는 함수를 만든후 여기선 값만 넘겨주고 cell에서 값이 매칭되기 하는 것이 좋을것같습니다.

2022-09-29 04:26 UTC, jaemuYeo requested changes
코멘트 반영하느라 고생많았습니다👍
이전처럼 구현상에 문제는 없지만 아쉬운 부분이 남아 몇가지 코멘트를 더 남겨놓았어요!!
그 외 추가 구현했으면 하는 부분과 전달내용을 남기겠습니다!

### cell 터치했을때
예제에서는 cell을 터치해서 디테일로 넘어갔다가 돌아오면 
선택했던 cell의 배경이 흰색으로 보입니다~
다만 두분의 코드에서는 
<img width="410" alt="스크린샷 2022-09-29 오후 12 27 48" src="https://user-images.githubusercontent.com/70311145/192934061-5766237d-c0e1-400d-ad13-f3983705914f.png">
이렇게 선택되었었다고 티를 내고있어요! 어떻게 해볼수있을까요??
다음 요청때 반영해보세요~

### View Life Cycle메서드 또는 코드의 위치
이건 동작에 이상이있는것도 아니고 정말 어딘가엔 사용하고도 있을 컨벤션일수있어
확답은 아니라는점 알아주세요!!
다만 저는 항상 VC의 프로퍼티 또는 아웃렛 변수 아래 생명주기 메서드를 배치한답니다.
그 다음으로는 액션함수 또는 다른 객체에서 사용할수있는 인터페이스 메서드,
그 다음으로 은닉화된 메서드 순서로 묶어서 관리하는 편이예요
처음부터 들인 습관이기도 하고 아직까지 재근과 또바기처럼 사용하는 사람을 본적이 없어서
전달해드린 것도 있고, 저는 제 방식이 조금 더 읽기 편하더라구요~
특히나 StartVC처럼 생명주기 메서드가 떨어져 있는 경우는 더욱이 본적이 없어요 ㅎㅎ
흐름은 코드가 추가되고 프로젝트가 수정되면서 어떻게 바뀔지도 모르구요!!
그렇기 때문에 비슷한 것끼리 묶어두고 관리하는게 아닌가 싶어요~
제 생각대로 흐름을 책으로 비교하면
타입명, 프로퍼티, 다양한 메서드들을 신문의 한페이지라 생각하고 비유해보세요!
결론은 저는 많은 사람들이 하고있는 컨벤션을 따라하다보니 습관이 되었다 입니다 🙂

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    override func awakeFromNib() {
필요한 오버라이딩일까요??
awakeFromNib 메서드는 무엇인가요?

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +        guard let nonOptionalItem = self.item else { return }
매개변수에 Item 타입을 가지고 있는데 굳이 옵셔널인 item프로퍼티를 바인딩해서 사용하는 이유가 있나요??🤔
item프로퍼티가 해당 Cell타입에 있어야하는 이유가 궁금합니다!

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    }
개행 아직 안됐어요 ㅎㅎ

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
setSelected를 오버라이딩 한 이유는 무엇인가요??

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +
불필요한 개행입니다!

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        if segue.identifier == "moveToDescription" {
segue의 식별자를 통해 구현한 이유가 무엇인가요??
guard let이 아닌 if let으로 바인딩 한 이유도 궁금합니다!
WorkDescriptionVC에서의 item과 해당 VC의 items를 잘 매칭시키면 조금 더 간결하게 구현해볼 수도 있을 거같아요~

```swift
// Hint

class WorkDescriptionVC: UIViewController {
    ,,,,

    func setItem(item: Item) {
        self.item = item
    }
}
```

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +extension KoreaWorkListViewController: UITableViewDelegate {
사용하지 않으면 없애주세요!

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        guard let cell = workListTableView.dequeueReusableCell(withIdentifier: "workListCell", for: indexPath) as? WorkListTableViewCell else { return UITableViewCell() }
전에 말했던 cell 식별자를 상수에 담아두라는 의미는 
```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let identifier = "workListCell"
        guard let cell = workListTableView.dequeueReusableCell(withIdentifier: identifier, for: indexPath) as? WorkListTableViewCell else {
        return UITableViewCell()
        }
        
        cell.configure(items[indexPath.row])
        
        return cell
    }
```
이런 형태입니다! return문 사이의 개행도 한번 봐주세요!
저렇게 담아쓰는 이유는 뭘까요?

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        cell.configure(items[indexPath.row])
configure라는 메서드를 통해 간결하게 구현한점 너무너무 좋아요 !! 👍

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +class StartViewController: UIViewController {
StartVC보다는 Main이 조금 더 명확할 거같아요!

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +            let result = numberFormatter.string(from: NSNumber(value: value))! + " 명"
느낌표가 보이네요 🙂

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/WorkDescriptionViewController.swift
> +    var item: Item?
이 친구는 외부에서 접근할 수 있나요??

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/WorkDescriptionViewController.swift
> +    }
개행해주세요~~

2022-09-29 04:26 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ParserJSON.swift
> +class ParserJSON {
이전에 제가 반복되는 코드를 줄이자는 말은 이런 의도가 아니였어요 ㅎㅎ
이전 프로젝트에서 사용했던 프로토콜과 제네릭 등을 사용해서 재사용이 가능한 코드를 만들도록 유도했었습니다!!
혹시 해볼 수 있을까요?? 스스로 시도해보고 어려움이 있다면 도움요청해주세요 💪

2022-09-29 05:06 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    override func awakeFromNib() {
## awakeFromNib() 
Nib 파일을 소스로 생성되는 객체가 초기화가 완료되면 이 메서드가 호출됩니다.
하지만 지금 현재 Nib파일은 쓰지 않아서 불필요한 메서드입니다.
삭제하겠습니다!

2022-09-29 05:07 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +        guard let nonOptionalItem = self.item else { return }
다시 생각해보니 cell이 item을 가지고있을이유가 전혀 없는것같습니다.

2022-09-29 05:08 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
필요없는 메서드인데 남겨둔것같습니다.

2022-09-29 05:21 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        if segue.identifier == "moveToDescription" {
storyBoard를 사용하는데 굳이 코드로 storyboard를 선언하여 연결하는 것은 비효율적이라고 생각하였습니다. 
이것 말고도 tableviewDelegate를 사용할 수 있지만 그렇게되면 storyboard를 선언해 연결해야되기 떄문입니다!
guard let을 쓰게 되면 항상 else가 따라오게됩니다. 지금은 스토리보드로 스그를 연결하여 옵셔널값이 나올일이 없기에 if let으로 else를 생략했습니다.

2022-09-29 05:21 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +extension KoreaWorkListViewController: UITableViewDelegate {
넵

2022-09-29 05:23 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        guard let cell = workListTableView.dequeueReusableCell(withIdentifier: "workListCell", for: indexPath) as? WorkListTableViewCell else { return UITableViewCell() }
cell의 identifier를 따로 선언하여 담음으로써 매직넘버를 없앨 수 있어서 인것같습니다.

2022-09-29 05:24 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        cell.configure(items[indexPath.row])
넵 ㅎㅎ

2022-09-29 05:24 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +class StartViewController: UIViewController {
수정하겠습니다

2022-09-29 05:24 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/WorkDescriptionViewController.swift
> +    var item: Item?
함수를 통해 값을 전달함으로 은닉화를 해주어야할것같네용

2022-09-29 05:25 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/WorkDescriptionViewController.swift
> +    }
넵

2022-09-29 05:25 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ParserJSON.swift
> +class ParserJSON {
넵

2022-09-29 05:26 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/StartViewController.swift
> +            let result = numberFormatter.string(from: NSNumber(value: value))! + " 명"
없애겠습니다 ‼️‼️‼️‼️

2022-09-29 05:26 UTC, wormsJJG commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +
넵

2022-10-04 07:11 UTC, jaemuYeo reviewed
또바기 재근 스텝2도 고생많았습니다!!
기능상의 문제는 크게 없기에 머지 진행할게요~
코멘트 남겨놓은 것은 참고해서 다음 스텝에 적용해보아도 좋을 거같아요 😀
많은 내용을 남겼는데 잘 반영해주느라 고생많았습니다!
스텝3에서 만나요 ㅎㅎ

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +
불필요한 개행이 있네요!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +    func configure(_ item: Item) {
무엇을 구성하는지에 대해 네이밍이 조금 더 명확하면 좋을 거같아요!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +
불필요한 개행이 있네요!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/Cell/WorkListTableViewCell.swift
> +        workShortDescription.text = .empty
불필요한 개행이 있네요!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/KoreaWorkListViewController.swift
> +        cell.selectionStyle = .none
예제에서는 선택할때 표시는 되지만 돌아갔을때는 선택되지 않게 보여져요!
하지만 현재는 아예 이팩트를 주지 않았군요?!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
이 곳에서 isNavigationBarHidden을 true로 주지않아도 정상적인 작동을 하고있는데
true로 해준 이유가 있나요?

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/WorkDescriptionViewController.swift
> +
불필요한 개행입니다!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/Mark.swift
> +enum Mark {
해당 객체의 속성들이 다른 곳에서도 쓰이는 상수가 아니라 Exposition타입의 포맷을 위한 것들이라면
Exposition 내부에 중첩 타입으로 관리해주어도 좋습니다!
다만 타입의 네이밍을 Mark로 한 이유는 무엇인가요?
조금 더 내용이 이어지게 지어보면 좋을 거같아요!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ParsedExposion.swift
> +    typealias JSONData = Exposition
별칭을 붙이지 않고 Exposition을 그대로 사용하는 것이 더 명확하지 않을까요??
두분의 생각은 어떠신가요!

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ParsedExposion.swift
> +    var fileName: String = "exposition"
다른 곳에 사용하지 않는다면 init내부에 선언해주세요!
값이 변경되지 않는다면 상수로 해주세요 😊

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ParsedItem.swift
> +    typealias JSONData = [Item]
이 별칭은 어떤 용도인가요?

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ParsedItem.swift
> +    var fileName: String = "items"
값이 변경되지 않는다면 상수로 선언해주세요!
해당 변수가 외부어디에도 쓰이지 않는다면 init메서드 내부에 작성해주어도 좋을 거같아요 ㅎㅎ

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Protocol/JSONParser.swift
> +protocol JSONParser {
프로토콜의 네이밍은 어떻게 지으면 좋을까요??
상황에 따라 다르게 표현하기도 하지만 ~able 을 붙여 네이밍한답니다 🙂

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Protocol/JSONParser.swift
> +    func parsingJSON(fileName: String) throws -> JSONData {
해당 메서드는 디코딩을 위한 메서드인데 조금 더 명확했으면 좋겠어요!
`decodeJSON` 처럼 지어준다면 어떨까요?

반환타입을 제네릭 (T 또는 다른네이밍)을 통해 준다면 조금 더 범용적으로 사용가능하지 않을까요??
associatedtype을 활용하지 않아도 될 것 같아요!!
하지만 제시했던 문제를 해결한 점은 너무 칭찬드립니다 👍💯

2022-10-04 07:11 UTC, jaemuYeo commented on Expo1900/Expo1900/Protocol/JSONParser.swift
> +            throw ExpoError.NilPersingData
이 곳에서의 에러는 파일의 이름등이 없을때 발생할 것같은데 에러케이스의 네이밍이 조금 더 명확하면 좋을 거같아요!

2022-10-04 07:11 UTC, merged