[STEP 2] 송만이, 에라
tasty-code/ios-exposition-universelle pull request #12
Opened 2022-09-29 03:07 UTC by seunghui5247

@jaemuYeo @wornsJJG 리뷰 부탁드립니다!

### **[STEP 2] 기능**

- [x] 첫번째, 두번째 화면 구성
- [x] cellDetail 화면 구성
- [x] header 가리기 

### **해결이 되지 않은 점**

2022-09-29 12:44 UTC, jaemuYeo requested changes
송만이 에라 고생많았습니다!!
이번 스텝에서는 데이터를 파싱해서 화면에 표현하는 것이 주된 목표인데
잘 구현해주었군요👏👏

다만 조금 아쉬운 부분들이 남아서 해당 코드마다 코멘트남겨놓았습니다!!
이해가 안되거나 해결되지 않은 부분이 있으면 언제든 디엠주세요!

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +    @IBOutlet weak var detailImage: UIImageView!
외부에서 접근할 일이 없다면 은닉화 해주는 것이 좋겠죠??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +    var item: ExpositionData? = nil
nil값을 초기화한 이유가 있나요??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +        guard let itemData = item else {
지금 처럼 한 방법도 틀리지는 않지만 보통 생명주기 메서드 내부에 기능 구현을 하지않고
하나하나의 구성을 해당 VC객체에 메서드로 만들어서 생명주기 메서드안에 호출한답니다 🙂

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +class TableViewCell: UITableViewCell {
1. 커스텀 셀도 하나의 그룹 및 파일을 만들어서 관리하면 좋습니다!

2. 해당 객체에서 셀을 구성해주는 메서드를 만든다면 DataSource에서 간단하게 함수호출만으로 구현할 수 있을 거같아요🤔

3. 해당 객체의 네이밍이 그냥 TableViewCell이군요! 조금 더 명확했으면 좋겠습니다
만약 50개의 페이지를 가진 프로젝트에서 40개가 테이블뷰이고 테이블뷰마다 커스텀셀이 2~3개씩 들어가있다면
각각의 네이밍이 달라야겠죠??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +    @IBOutlet weak var workImage: UIImageView!
workImageView 처럼 타입명을 명확하게 연결하여 네이밍 해주세요!

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +class ExpoItemViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
보통 테이블뷰나 컬렉션뷰를 구현하거나 그 외에 여러 방면에서 extension을 통해 VC를 구현한답니다~
```swift
class ViewController: UIViewController {

}

extension ViewController: UITableViewDataSource {

}

extension ViewController: UITableViewDelegate {

}
```

이렇게 구현하는 이유는 무엇일까요??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +    var items: [ExpositionData]? = nil
이 프로퍼티의 네이밍은 items인데 타입은 ExpositionData군요!!
타입명을 Item으로 바꾸면 조금 더 명확하고 잘 매칭될 거같아요 ㅎㅎ

해당 프로퍼티를 옵셔널로 선언한 이유는 무엇인가요??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +        let cell: TableViewCell = tableView.dequeueReusableCell(withIdentifier: "tableViewCell", for: indexPath) as! TableViewCell
느낌표 사용을 지양해주세요!!

identifier 같은 경우는 매직넘버의 개념처럼 따로 상수에 저장후 넣어주는 것이 좋아요~

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +    override func viewDidLoad() {
보통의 컨벤션은 아웃렛변수 또는 프로퍼티 바로아래 생명주기들을 관리한답니다!!
생명주기를 제일 아래 배치한 이유가 있나요??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +        guard let expoData: NSDataAsset = NSDataAsset.init(name: "items") else {
해당 구현부도 기능구현을 나누어 메서드를 구현하고 호출하는 방식으로 바꿔보세요~~

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoLaunchViewController.swift
> +class ExpoLaunchViewController: UIViewController {
현재 VC의 네이밍보다 메인화면이니 MainViewController 와 같은 네이밍은 어떤가요??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoLaunchViewController.swift
> +    @IBOutlet weak var expoTitle: UILabel!
아웃렛 변수의 네이밍을 지을때에는 보통 해당 타입을 붙여서 네이밍하는 편입니다~
expo는 제외해도 될거같아요!!
예를들면 `titleLabel, titleImageView` 등이 있습니다!

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoLaunchViewController.swift
> +    var info: ExpoDesc? = nil
nil로 초기화한 이유가 있나요??
info의 타입명은 ExpoDesc인데 네이밍을 info로 지었군요!
타입명과 매칭해도 될거같다 생각하는데 두분의 의견은 어떤가요??

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoLaunchViewController.swift
> +        guard let expoData: NSDataAsset = NSDataAsset.init(name: "exposition_universelle_1900") else {
위에서 말한것처럼 생명주기 메서드에 기능을 구현하지 않고,
기능별로 메서드를 만들어서 호출해주면 좋을 것같아요!!

그리고 현재 VC에서 파싱을 해주고있는데 지금처럼 말고
파싱을 해주는 타입을 만들어서 사용해볼 수 있을까요??
프로토콜과 제네릭을 활용하여 재사용이 가능하게 만들어보면 좋을 것 같아요!!
진행하다 어려우면 언제든 불러주세요~~

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/JSONModel.swift
>  struct ExpoDesc: Decodable {
저번에도 전달했던 얘기입니다~!
Desc처럼 줄인 표현보다 명확하게 표현해주면 좋을 거같아요☺️

2022-09-29 12:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/JSONModel.swift
> +    let visitors: Int
해당 프로퍼티의 타입이 틀렸었군요! 잘 찾아냈어요 👍

2022-09-30 04:41 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +        guard let itemData = item else {
혹 재사용성이 없다고 하더라도, 메서드의 기능을 네이밍을 통해 이해하기 위해서 해당 방법을 사용하는걸까요?

2022-09-30 04:43 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +class ExpoItemViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
분리해서 보기 위함이라고 생각합니다. tableView의 함수가 UIViewController내부에 함수가 쌓여있으면 보기 불편할거라 생각됩니다.

2022-09-30 04:43 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +    var items: [ExpositionData]? = nil
다시보니 빈 객체로 선언해도 된다고 생각되네요.
nil은 빈 값을 의미하고, 값이 로딩되기 전 없다는  표시를 하고 싶었습니다.

2022-09-30 04:44 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +        let cell: TableViewCell = tableView.dequeueReusableCell(withIdentifier: "tableViewCell", for: indexPath) as! TableViewCell
오... 감사합니다! as는 fix과정중 들어간지 몰랐네요 ㅎㅎ ㅠ

2022-09-30 04:44 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +    override func viewDidLoad() {
음.. 딱히 없었습니다! fix를 누르니 위쪽에 배치되는 함수가 있었어서 그랬습니다! 수정하겠습니다!

2022-09-30 06:00 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +    var item: ExpositionData? = nil
할당되지 않은 값이라고 생각하였습니다. 기본값을 주기보단 nil을 주는 방향으로 고려하였습니다.

2022-10-04 05:18 UTC, kr-yeon commented on Expo1900/Expo1900/Controller/ExpoLaunchViewController.swift
> +    var info: ExpoDesc? = nil
기본적인 값을 채워넣어도 되지만, nil이라는 없는 값이라는걸 주는게 더 매력적으로 보였습ㄴ다.

nil이란 아직 값이 없는 상태이고, 값을 로딩하지 못함에도 기본적인 값을 띄워주는 것이 마음에 들지 않네요.

2022-10-04 06:19 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +        guard let itemData = item else {
넵! 코드의 가독성 측면에서 기능별로 만들어서 호출해주는 편입니다!!
또한 생명주기 메서드는 '화면이 ~일때 ~을 할게!' 와 같은 기능을 하는데
많은 기능을 필요로 한다면 해당 메서드만의 역할이 사라지겠죠??
저희가 교육 초기에 했던 프로젝트에서 함수별로 기능분리를 계속 연습한 이유가 있답니다 😀

2022-10-04 08:20 UTC, jaemuYeo requested changes
송만이 에라 리뷰반영하느라 고생많았습니다 👏
대부분 잘 구현해주었는데 아직 아쉬운 부분이 남아서 몇가지 더 코멘트 남겨보았어요!!
한 번 더 반영해보고 하다가 궁금한 부분이 생기면 언제든 불러주세요 화이팅!! 💪

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +				C79FF4B82589F401005FB0FD /* MainViewController.swift */,
순서별로 정렬되면 더 보기 좋을 거같아요!! ☺️

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoDataTableViewCell.swift
> +class ExpoDataTableViewCell: UITableViewCell {
해당 타입은 Cell이란 그룹 안에 보관해보는건 어떨까요?

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +    var item: ExpositionData? = nil
저번에 이어 또한번 전달해요~
nil또는 기본값을 준경우와 옵셔널 타입만 주었을때에 해당 타입의 인스턴스를 생성하면 메모리에서 어떤 차이점이 있을까요??
그리고 이 변수를 사용하는 곳에서 값이 nil이 될 경우 nil을 할당해줄텐데
꼭 기본값으로 주어야하는지에 대해서도 궁금하네요 🤔

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +        if let itemData = item {
setView와 같은 메서드를 통해 item을 옵셔널 바인딩하고 값들을 넣어주면
하나의 메서드를 통해 구현할 수 있을 거같아요!!

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +    func setTitle(in title: String) {
아래 메서드들은 외부에서 사용되지 않는다면 은닉화해주세요!

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +        guard let expoData: NSDataAsset = NSDataAsset.init(name: "items") else {
MainVC의 코멘트를 참고하여 시도해보세요~~!

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +        guard let cell: ExpoDataTableViewCell = tableView.dequeueReusableCell(withIdentifier: "tableViewCell", for: indexPath) as? ExpoDataTableViewCell else {
보통 identifier의 String값도 매직넘버로 간주한답니다 ㅎㅎ
해당 메서드에 상수에 값을 넣어서 사용하면 좋을 거같아요~~
itentifier를 해석하면 식별자를 뜻하는데 tableViewCell은 너무 범용적인 표현같아요!
해당 셀만의 특별한 식별자값을 주면 좋을 것 같습니다!

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/ExpoItemViewController.swift
> +extension ExpoItemViewController: UITableViewDelegate {}
사용하지 않는다면 제거해주세요!

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    @IBOutlet weak var titleLabel: UILabel!
다른 VC들과 달리 이곳에서는 아웃렛변수에 대해 은닉화를 해주지 않았군요~~

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        guard let expoInfo: NSDataAsset = NSDataAsset.init(name: "exposition_universelle_1900") else {
현재 디코딩을 해주어야하는 곳에서 같은 코드들이 반복되고 있어요!!
JSONDecodable이라는 프로토콜을 만들고 해당 프로토콜에 기본값을 주는 메서드를 만들어서
해결해보면 조금 더 재사용성있고 간결하게 사용가능할 것같습니다~ 한 번 시도해볼 수 있을까요??
구글링을 통해 검색해보면 많은 자료가 나올거예요 😀
Hint. 제네릭 활용

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +            imageView.image = UIImage(named: "poster")
이건 스토리보드 상에서도 처리해줄 수 있을 거같네요!

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +            visitorCountLabel.text = ": " + String(expoInfo.visitors)
`:`와 같은 매직넘버를 어떻게 처리해볼 수 있을까요?? 🤔

2022-10-04 08:20 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
viewDidLoad와 viewWillAppear메서드가 따로 놀고있군요! 한 곳에 정렬해주세요~

2022-10-06 06:36 UTC, jaemuYeo reviewed
스텝2도 고생많았습니다!! 👍
많은 내용을 코멘트에 남겼는데 잘 반영해주었어요!! ㅎㅎ
머지 진행하겠습니다!
몇가지 코멘트 남겼는데 확인 후 넘어가주세요~

2022-10-06 06:36 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    let labelMagicNumber = ": "
현재 네이밍보다는 `콜론`이라는 간단한 네이밍도 괜찮아요!
그리고 이런 매직 넘버는
```swift
enum Constants {
    static let colon = ":"
}
// 또는

extension String {
    static let colon = ":"
}
```
처럼 관리한답니다! 객체의 위치는 사용하려는 타입이 하나인 경우 중첩타입으로 관리하기도 하며
여러 파일에서 사용할 경우 새로운 파일을 만들어서 관리하기도 해요~

2022-10-06 06:36 UTC, jaemuYeo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        super.viewDidLoad()
super와 메서드 호출 사이에 한번 개행해주면 더 보기 좋을 거같습니다 🙂

2022-10-06 06:36 UTC, jaemuYeo commented on Expo1900/Expo1900/Protocol/JSONDecodable.swift
> +    func decodeJSON<U: Decodable>(of name: String) throws -> U {
제네릭의 U는 무엇을 의미하며 U로 하였나요?

2022-10-06 06:36 UTC, merged