[STEP 1] 씨유, 도도
tasty-code/ios-exposition-universelle pull request #3
Opened 2022-09-20 06:33 UTC by Schro2109

# 작업 내용
1. JSON 파일을 변환해 저장할 Relic 타입 구현
2. Relic 타입 내부에 CodingKey를 이용해 키값을 연결해줄 열거체 CodingKeys 추가

2022-09-20 07:57 UTC, jaemuYeo requested changes
수고하셨어요 씨유 도도 👏
많은 내용이 있지 않아 간단하게 코멘트 남길게요!
그리고 프로젝트 시작 전 아키텍처에 맞게 그룹과 파일들을 항상 배치하는 습관도 들여보세요 😀
JSON그룹은 Model로 해도 될것같아요~

그리고 또하나 dataset이 있는데 그 모델은 구현하지 않았네요!

2022-09-20 07:57 UTC, jaemuYeo commented on Expo1900/Expo1900/Assets.xcassets/AccentColor.colorset/Contents.json
> +  "info" : {
이 곳에서 1x, 2x, 3x들은 무엇을 뜻할까요??

2022-09-20 07:57 UTC, jaemuYeo commented on Expo1900/Expo1900/JSON/Relic.swift
> +struct Relic: Codable {
Codable을 채택한 이유가 있나요??
타입명도 JSON 파일과 비슷하게 가도 괜찮아요! 
단 JSON파일은 복수형이니 Item 과 같이요 ~
이건 필수가아니니 두분의 의견대로 진행해주세요!

2022-09-20 07:57 UTC, jaemuYeo commented on Expo1900/Expo1900/JSON/Relic.swift
> +    var name: String
이 곳의 프로퍼티들을 변수로 선언한 이유가 있나요?

2022-09-20 07:57 UTC, jaemuYeo commented on Expo1900/Expo1900/JSON/Relic.swift
> +    var shortDesc: String
웬만하면 축약된 단어보다는 shortDescription 처럼 명확하게 해주는 것이 좋습니다!

2022-09-20 07:57 UTC, jaemuYeo commented on Expo1900/Expo1900/JSON/Relic.swift
> +    var desc: String
여기도 description이 좋겠네요 :)

2022-09-20 07:57 UTC, jaemuYeo commented on Expo1900/Expo1900/JSON/Relic.swift
> +    enum CodingKeys: String, CodingKey {
CodingKey를 잘 활용하셨네요 💯

2022-09-21 00:51 UTC, dddowon commented on Expo1900/Expo1900/JSON/Relic.swift
> +    var shortDesc: String
넵

2022-09-21 00:58 UTC, dddowon commented on Expo1900/Expo1900/JSON/Relic.swift
> +struct Relic: Codable {
넵! Codable을 채택한 이유는 저희가 모델 구현 후 JSON 파일을 asset으로 추가해주고 decoder를 사용하기 위해 채택했습니다!

2022-09-21 01:04 UTC, dddowon commented on Expo1900/Expo1900/JSON/Relic.swift
> +    enum CodingKeys: String, CodingKey {
감사함다

2022-09-21 01:15 UTC, Schro2109 commented on Expo1900/Expo1900/JSON/Relic.swift
> +    var name: String
객체 생성 시에 상수로 값을 할당하는 방법을 미처 생각하지 못했네요
상수 형식으로 바꿔보겠습니다!

2022-09-21 01:23 UTC, Schro2109 commented on Expo1900/Expo1900/Assets.xcassets/AccentColor.colorset/Contents.json
> +  "info" : {
찾아보니 휴대폰 기종마다 이미지 표현에 필요로 하는 픽셀의 갯수가 다르기 때문에 그에 맞춰 3가지의 각기 다른 배율을 가진 이미지가 준비되어 있는 것 같습니다!

2022-09-21 01:25 UTC, jaemuYeo commented on Expo1900/Expo1900/JSON/Relic.swift
> +struct Relic: Codable {
Decodable만 채택해도 되는데 Codable을 한 이유가 궁금했어요!
큰 문제가 될건 아닙니다 😀

2022-09-21 01:31 UTC, dddowon commented on Expo1900/Expo1900/JSON/Relic.swift
> +struct Relic: Codable {
아아 인코딩은 사용하지 않군요!

2022-09-21 02:12 UTC, Schro2109 commented on Expo1900/Expo1900/JSON/Relic.swift
> +    var name: String
하나의 객체로 여러 데이터들을 표현하려고 변수로 선언했으나
다시 생각해보니 앱의 취지와는 다른 것 같아 상수로 선언 후 여러 객체를 만드는 방식으로 수정했습니다!

2022-09-21 02:18 UTC, jaemuYeo reviewed
스텝1 고생많았습니다 👍
이제 본격적으로 UI에 도전해보세요!! 화이팅 😄

2022-09-21 02:18 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/Expo.swift
> +struct Expo: Decodable {
좋아요! 다만 Expo도 축약된 표현 같은데 Exposition 처럼 명확하게 해주면 좋을 거같아요!!

2022-09-21 02:18 UTC, merged