Step01_ jaegeun, ttobagi
tasty-code/ios-exposition-universelle pull request #7
Opened 2022-09-20 07:21 UTC by moonsoungjin

Step01: JSON 모델 타입 구현

```
struct ExpoData: Codable { // 디코딩과 인코딩을 위해 codeable를 사용
  var name: String
  var imageName: String
  var shortDesc: String
  var desc: String

  enum CodingKeys: String, CodingKey { // json파일 name과 변수이름이 다르기때문에 codingKey사용
      case name
      case imageName = "image_name"
      case shortDesc = "short_desc"
      case desc
  }
}
```

2022-09-20 08:08 UTC, jaemuYeo requested changes
고생했습니다 재근 또바기! 👏
많은 내용이 있지않기에 간단히 코멘트 남겨놓았어요!!

현재 Items 이 외에 또 하나의 JSON dataset이 있는데 그 것은 모델 구현을 하지 않았군요!

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ExopoData.swift
> +struct ExpoData: Codable {
인코딩을 사용하지 않는데 Codable을 채택한 이유가 있나요??

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ExopoData.swift
> +    var name: String
속성들을 변수로 선언된 이유가 있나요?

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ExopoData.swift
> +    var shortDesc: String
축약된 단어보단 shortDescription 처럼 명확하게 해주는 것이 좋아요!
어차피 아래서 CodingKey를 통해 매칭해주잖아요😀

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ExopoData.swift
> +    var desc: String
여기도 description이 좋겠네요!

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ExopoData.swift
> +        case name
변경하지 않아도 되는 것들은 하나의 케이스에 나열해도 됩니다!

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/View/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "scale" : "2x",
이 곳에 있는 1x, 2x, 3x는 무엇을 뜻할까요?? 🤔

2022-09-20 08:08 UTC, jaemuYeo commented on Expo1900/Expo1900/items.json
> +[
이 파일은 왜 추가해놓았나요??

2022-09-21 00:42 UTC, wormsJJG commented on Expo1900/Expo1900/View/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "scale" : "2x",
바뀌는 해상도에 대응하기위해 정해놓은 사이즈입니다!

2022-09-21 00:43 UTC, wormsJJG commented on Expo1900/Expo1900/items.json
> +[
Test를 해보려고 추가해보았는데 모델타입만 구현했습니다.

2022-09-21 00:43 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ExopoData.swift
> +        case name
넵

2022-09-21 00:43 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ExopoData.swift
> +    var desc: String
넵

2022-09-21 00:43 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ExopoData.swift
> +    var shortDesc: String
넵

2022-09-21 00:44 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ExopoData.swift
> +    var name: String
데이터를 담기위해서입니다

2022-09-21 00:45 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ExopoData.swift
> +struct ExpoData: Codable {
디코딩만해서 decodable을 채택해도 될것같네요!

2022-09-21 01:35 UTC, jaemuYeo requested changes
코멘트 남겼습니다~ 확인 후 반영해주세요!

2022-09-21 01:35 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ItemsData.swift
> +struct ItemsData: Decodable {
ㅇㅇ 데이터라는 네이밍 보다는 간단하 Item으로만 해주어도 될 것같아요

2022-09-21 01:35 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ItemsData.swift
> +    var name: String
지난 코멘트에 변수로 한 이유에 대해 물어본 것은 `mutable`한 값이어야 할까?에 대한 질문이었습니다~
상수로 선언해도 되지 않을까요?

2022-09-21 01:35 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ItemsData.swift
> +struct ExpoData: Decodable {
ItemData.swift파일에 ExpoData도 함께 있어야 할까요?
위의 내용과 마찬가지로 네이밍을 Exposition 처럼 하면 어떨까요?

2022-09-21 01:35 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/ItemsData.swift
> +    enum CodingKeys: String, CodingKey {
이 친구의 용도는 무엇인가요?
이 타입에서 필요할까요?

2022-09-21 02:12 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ItemsData.swift
> +struct ItemsData: Decodable {
넵

2022-09-21 02:12 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ItemsData.swift
> +    var name: String
적용하겠습니다

2022-09-21 02:12 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ItemsData.swift
> +struct ExpoData: Decodable {
넵!

2022-09-21 02:13 UTC, wormsJJG commented on Expo1900/Expo1900/Model/ItemsData.swift
> +    enum CodingKeys: String, CodingKey {
이친구는 상수명과 api 키값이랑 똑같기때문에 필요없습니다

2022-09-21 02:22 UTC, jaemuYeo reviewed
스텝1 고생많았습니다!!
커밋 메시지에 `pr 반영` 이렇게 하지않고 수정된 내용으로 남겨주세요 🙂
머지진행할게요! 다음스텝에서 만나요~

2022-09-21 02:23 UTC, merged