[STEP 1] uno, rookie, poodle
tasty-code/ios-exposition-universelle pull request #9
Opened 2022-09-21 03:21 UTC by parkseyoon

@jaemuYeo 코드 리뷰 부탁드립니다 :)

# 작업 내용
- EntryResponse 타입 구현

2022-09-21 06:04 UTC, jaemuYeo requested changes
우노 루키 푸들 스텝1 고생했습니다!
이번 스텝은 큰 내용을 다루지 않아 간단한 코멘트 남겨놓을게요!
그룹 및 파일도 MVC패턴에 맞게 구성하면 좋을 것같아요!
항상 프로젝트 시작전 작업을 먼저 해놓는 습관을 들이는 것도 좋습니다 😀

첨부된 이미지와 데이터도 assets에 추가해보면 좋을 것같아요~

그리고 현재 푸들저장소 STEP1에서 PR이 왔는데 다음스텝에서는 main에 병합해서 PR보내주세요!

2022-09-21 06:04 UTC, jaemuYeo commented on Expo1900/Expo1900/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "scale" : "2x",
이 곳에 있는 1x, 2x, 3x는 무엇을 뜻할까요?

2022-09-21 06:04 UTC, jaemuYeo commented on Expo1900/Expo1900/EntryResponse.swift
> +struct ParisEntryResponse: Decodable {
디코딩만을 위한 Decodable채택 좋습니다 👍

이 타입의 네이밍은 왜 ParisEntryResponse로 했나요??
간단히 `전시회`같은 네이밍도 괜찮을 것같아요!
만약 이 타입을 통해 파리 뿐만아니라 서울, 뉴욕 등등의 데이터도 가져온다 생각해보고
재사용성이 용이하게하면 좋습니다!

2022-09-21 06:04 UTC, jaemuYeo commented on Expo1900/Expo1900/EntryResponse.swift
> +    let title: String
상수로 잘 선언해 주었군요!

2022-09-21 06:04 UTC, jaemuYeo commented on Expo1900/Expo1900/EntryResponse.swift
> +struct KoreaEntryResponse: Decodable {
이 타입의 네이밍도 위의 내용을 참고해 반영해보세요!

2022-09-21 06:04 UTC, jaemuYeo commented on Expo1900/Expo1900/EntryResponse.swift
> +    let shortDesc: String
desc는 Description의 줄인 표현입니다.
항상 명확하게 해주는게 좋아요~~ 
shortDescription, description과 같이 수정해보아요 🤗

2022-09-21 07:07 UTC, eunho8713 commented on Expo1900/Expo1900/EntryResponse.swift
> +struct ParisEntryResponse: Decodable {
간단하게 전시회같은 네이밍이 더 좋겠네요! 파리 만국박람회 데이터를 받아오는것이라서 네이밍을 고민하다 ParisEntryResponse로 하게되었습니다.

2022-09-21 07:08 UTC, eunho8713 commented on Expo1900/Expo1900/EntryResponse.swift
> +    let title: String
😎

2022-09-21 07:20 UTC, chaeyoon1101 commented on Expo1900/Expo1900/EntryResponse.swift
> +struct KoreaEntryResponse: Decodable {
넵 변경해보겠습니다

2022-09-21 07:20 UTC, chaeyoon1101 commented on Expo1900/Expo1900/EntryResponse.swift
> +    let shortDesc: String
넵 수정하였습니다

2022-09-21 07:20 UTC, eunho8713 commented on Expo1900/Expo1900/EntryResponse.swift
> +struct KoreaEntryResponse: Decodable {
넵 !

2022-09-21 07:21 UTC, eunho8713 commented on Expo1900/Expo1900/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "scale" : "2x",
이미지에 사이즈인것 같습니다

2022-09-22 05:44 UTC, jaemuYeo reviewed
우루프 스텝1 고생많았습니다!
머지 진행할게요!
다음 스텝에서 이번 코멘트에 대해 반영하며 진행해주세요~
에셋에 넣은 컨텐츠는 일부러 파일 채로 넣은 건가요??

2022-09-22 05:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/EntryResponse.swift
> +struct WorkPieceInformation: Decodable {
파일명을 객체이름과 동일하게 하고
두 모델을 따로 관리하면 좋을 것같아요~

2022-09-22 05:44 UTC, jaemuYeo commented on Expo1900/Expo1900/Model/EntryResponse.swift
> +        case name
커스텀이 필요하지 않은 케이스들은 한곳에 나열하여도 좋습니다 !

2022-09-22 05:44 UTC, merged

2022-09-22 07:48 UTC, parkseyoon commented on Expo1900/Expo1900/Model/EntryResponse.swift
> +struct WorkPieceInformation: Decodable {
따로 파일을 만들어 분리하였습니다!

2022-09-22 07:49 UTC, parkseyoon commented on Expo1900/Expo1900/Model/EntryResponse.swift
> +        case name
case 위치를 바꾸어 읽기 쉽게 정리하였습니다!